Post.create(title: "Post 1", description: "post desc 1")
Post.create(title: "Post 2", description: "post desc 2")
Post.create(title: "Post 3", description: "post desc 3")
Post.create(title: "Post 4", description: "post desc 4")
Post.create(title: "Post 5", description: "post desc 5")
Post.create(title: "Post 6", description: "post desc 6")